---
- name: Ensure git user configuration exists
  community.general.git_config:
    name: "{{ item.key }}"
    scope: global
    value: "{{ item.value }}"
  loop: "{{ workspace_git_config | dict2items }}"
  tags:
    - setup
    - development
    - git
    - configuration
