---
- name: Verify this is a Debian-based system
  ansible.builtin.fail:
    msg: "This role only supports Debian/Ubuntu systems"
  when: ansible_os_family != "Debian"
  tags: ['always']

# Base system setup
- name: Include debian-specific tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == "Debian"
  tags:
    - setup
    - packages
    - base

# Shell environment setup
- name: Include shell configuration tasks
  ansible.builtin.include_tasks: shell.yml
  tags:
    - setup
    - shell
    - environment

# Development tools setup
- name: Include git configuration tasks
  ansible.builtin.include_tasks: git.yml
  tags:
    - setup
    - development
    - git

# Terminal emulator setup
- name: Include terminator configuration tasks
  ansible.builtin.include_tasks: terminator.yml
  tags:
    - setup
    - terminal
    - terminator

# Uninstall capability
- name: Include uninstall tasks
  ansible.builtin.include_tasks: uninstall.yml
  tags: ['never', 'uninstall']
