---
- name: Reload bash configuration
  ansible.builtin.shell: source {{ ansible_env.HOME }}/.bashrc
  args:
    executable: /bin/bash
  listen: reload bash
  register: bashrc_reload
  failed_when: bashrc_reload.rc != 0
  changed_when: bashrc_reload.rc == 0
  ignore_errors: true
